### ISSUE TITLE
Functions that should be public are Private

### ISSUE THREAD

**Issue by dougchristie-DukeEnergy** [dss-extensions/AltDSS-Go#4]
There are a lot of function in dsslib.go that are private but need to be made public.    Note all functions that start with a lowercase are private and cannot be accessed in the package. For example puVmagAngle() in dsslib.go is private and not public and cannot be used with an instance of *IBus, it same with kVBase as well.

**Comment by dougchristie-DukeEnergy** [comment]
I can make some of these changes if you do not mind me doing that? I did make the change locally and imported my local package and tried it out with my code and it worked.

**Comment by PMeira** [comment]
Thanks for pointing these. Let me think a bit about it first. 
It seems there are at least 51 functions. Of those, 30 can be adjusted without issues (`puVmagAngle` is fine as `PUVMagAngle`, so is `kVArated` as `RatedkVA`). The remaining 21 are mostly variations on `kV`, `kVA`, `kvar` and `kW`. Maybe something in the style of `VoltageskV` or `Voltages_kV` works. I'll review these 21 cases to see what fits better and push a commit later today.

(I personally don't like using pure units as names since that's vague, but OpenDSS uses that convention in a lot of places)

**Comment by PMeira** [comment]
Actually, looks like since most `k...` function are properties (`Get_k...`/`Set_k...`), only these 8 were changed: :smile: 


| Struct | Old name | New name |
| :-- | :-- | :-- |
| IBus | kVBase | Get\_kVBase |
| IBus | puVLL | PUVLL |
| IBus | puVmagAngle | PUVMagAngle |
| IBus | puVoltages | PUVoltages |
| IMonitors | dblFreq | DblFreq |
| IMonitors | dblHour | DblHour |
| ITransformers | strWdgCurrents | StrWdgCurrents |
| IPVSystems | kW | Get\_kW |

**Comment by dougchristie-DukeEnergy** [comment]
Thanks for the fix I appreciate it.
